### ISSUE TITLE
Add additional metrics for Disk check

### ISSUE THREAD

**Issue by riklempens** [infrasonar/synology-probe#3]
Add additional metrics for Disk check.

We currently retrieve these metrics:

OID | Name
----|--------------
.3  | Model
.5  | Status
.6  | Temperature
.4  | Type

From the [Synology documentation](https://global.download.synology.com/download/Document/Software/DeveloperGuide/Firmware/DSM/All/enu/Synology_DiskStation_MIB_Guide.pdf):

OID |  Name            | Type    | Status Type | Explanation                                                       | Supported OS
----|------------------|---------|-------------|-------------------------------------------------------------------|------------------
.1  | diskIndex        | Integer | -           | Used internally for SNMP table and not accessible                 | DSM, DSM UC
.2  | diskID           | String  | -           | Disk name in DSM                                                  | DSM, DSM UC
.3  | diskModel        | String  | -           | Disk model                                                        | DSM, DSM UC
.4  | diskType         | String  | -           | Disk type, e.g. SATA, SSD                                         | DSM, DSM UC
.5  | diskStatus       | Integer | Normal(1)*  | Current disk status                                               | DSM, DSM UC
.6  | diskTemperature  | Integer | -           | Disk temperature                                                  | DSM, DSM UC
.7  | diskRole         | String  | data *      | The role of the disk in system                                    | DSM 7.0 and above
.8  | diskRetry        | Integer | -           | The count of each disk connection retries                         | DSM 7.0 and above
.9  | diskBadSector    | Integer | -           | The count of each disk I/O bad sector                             | DSM 7.0 and above
.10 | diskIdentifyFail | Integer | -           | The count of each disk identify fails                             | DSM 7.0 and above
.11 | diskRemainLife   | Integer | -           | The estimate remain life of each disk                             | DSM 7.0 and above
.12 | diskName         | String  | -           | Disk name which will keep the same value in different DSM version | DSM 7.0 and above
.13 | diskHealthStatus | Integer | Normal(1)*  | Current disk health status                                        | DSM 7.1 and above

Please note we need to "translate" the status.

**Comment by riklempens** [comment]
@Koos85 

Please add "translation" for `diskHealthStatus`

\# | Status   | Explanation                         | Supported OS
---|----------|-------------------------------------|---------------------
1  | Normal   | The disk health status is normal.   | DSM 7.1 and above
2  | Warning  | The disk health status is warning.  | DSM 7.1 and above
3  | Critical | The disk health status is critical. | DSM 7.1 and above
4  | Failing  | The disk health status is failing.  | DSM 7.1 and above

**Comment by Koos85** [comment]
Also changed itemname. We now use diskName instead of diskID

**Comment by riklempens** [comment]
Working as should, closing this issue.
